import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useCountry } from '../../app/hooks/useCountry';
import styles from '../../styles/Home.module.css';

const Country: NextPage = () => {
  const { query } = useRouter();
  const { isLoading, country, error } = useCountry(String(query?.id));

  return (
    <div className={styles.container}>
      <Head>
        <title>{country?.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>{country?.name}</h1>
        {error && <div style={{ color: 'red' }}>{(error as any).message}</div>}

        {isLoading ? (
          <h1>Loading...</h1>
        ) : (
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>{country?.name}</h2>
              <p>{country?.description}</p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Country;
