import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useMutation } from 'react-query';
import styles from '../styles/Home.module.css';
import { CountryService, ICountry } from '../app/services/country.service';

const Country: NextPage = () => {
  const [data, setData] = useState<ICountry>({
    id: 0,
    name: '',
    description: '',
  } as ICountry);

  const { push } = useRouter();
  const { isLoading, mutateAsync } = useMutation(
    'create country',
    (data: ICountry) => CountryService.create(data),
    {
      onSuccess: () => {
        push('/');
      },
      onError: (error: any) => {
        alert(error.message);
      },
    }
  );

  const handleOnSubmit = async (e: any) => {
    console.log(data);
    e.preventDefault();
    await mutateAsync(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Add Country</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Add Country</h1>
        <form onSubmit={e => handleOnSubmit(e)} className={styles.form}>
          <input
            type='text'
            placeholder='Enter ID'
            value={data.id}
            onChange={e => setData({ ...data, id: +e.target.value })}
          />
          <input
            type='text'
            placeholder='Enter country name'
            value={data.name}
            onChange={e => setData({ ...data, name: e.target.value })}
          />
          <input
            type='text'
            placeholder='Enter country description'
            value={data.description}
            onChange={e => setData({ ...data, description: e.target.value })}
          />
          <button disabled={isLoading}>Create</button>
        </form>
      </main>
    </div>
  );
};

export default Country;
