import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { useCountries } from '../app/hooks/useCountries';

import { CountryService, ICountry } from '../app/services/country.service';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { isLoading, countries, error } = useCountries();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>React Query</h1>
        {error && <div style={{ color: 'red' }}>{(error as any).message}</div>}

        {isLoading ? (
          <h1>Loading...</h1>
        ) : countries?.length ? (
          <div className={styles.grid}>
            {countries.map(country => (
              <a
                key={country.id}
                href='https://nextjs.org/docs'
                className={styles.card}>
                <h2>{country.name}</h2>
                <p>{country.description}</p>
              </a>
            ))}
          </div>
        ) : (
          <h1>Elements not found</h1>
        )}
      </main>
    </div>
  );
};

export default Home;
