import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useQuery } from 'react-query';
import { CountryService } from '../app/services/country.service';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const {
    isLoading,
    data: response,
    error,
    status,
  } = useQuery('county list', () => CountryService.getAll());

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {isLoading ? (
          <h1>Loading...</h1>
        ) : response?.data.length ? (
          <div className={styles.grid}>
            {response.data.map(country => (
              <a
                key={country.id}
                href='https://nextjs.org/docs'
                className={styles.card}>
                <h2>{country.name}</h2>
                <p>{country.description}</p>
              </a>
            ))}
          </div>
        ) : (
          <h1>Elements not found</h1>
        )}
      </main>
    </div>
  );
};

export default Home;
